server:
  env: 'DEV'
  addr: '0.0.0.0:8090'

openweather:
  url: 'https://api.openweathermap.org/data/2.5'
  apikey: 'd0562f476913da692a065c608d0539f6'

db:
  addr: 'host=127.0.0.1 user=changeuser password=changeme dbname=promocodedb port=5432 sslmode=disable TimeZone=UTC'

telemetry:
  addr: '127.0.0.1:4317'

logs:
  level: 'DEBUG'